version: '3'

services:
  php:
    build: .docker/php
    image: php:7.2
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=groups
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - php

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:
